version: '3.9'

services:

  postgres:
    image: postgres:13.8-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout:  3s
      retries: 3
    networks:
      - backend_nw

  api:
    image: tsorokoletova/diplom_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
       condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/ping/ || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - backend_nw
      - frontend_nw
    volumes:
      - ./nginx/static/:/opt/static/
  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
       condition: service_healthy
    networks:
      - frontend_nw
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static/:/opt/static/

volumes:
  postgres_data_todolist:

networks:
  backend_nw:
    driver: bridge
  frontend_nw:
    driver: bridge
