# Generated by Django 4.1 on 2022-10-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0006_alter_goal_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={
                "ordering": ["title"],
                "verbose_name": "Доска",
                "verbose_name_plural": "Доски",
            },
        ),
    ]
