name: Build and deploy action
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      DEBUG: True
      SECRET_KEY: 123456789
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      VK_OAUTH2_KEY: 12351439253
      VK_OAUTH2_SECRET: 12351439253
      BOT_TOKEN: 577988154187765
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create env file and build image
        run: |
          env >.env
          docker-compose build
      - name: run tests
        run: | 
          docker-compose run --rm api python manage.py test
  build:
    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/diplom_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/diplom_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
     runs-on: ubuntu-22.04
     needs: build
     env:
       ANSIBLE_VAULT_PASSWORD_FILE: /tmp/.vault_pass.txt
     steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: render template
       run: |
         echo "${{ secrets.VAULT_PASSWORD }}" > /tmp/.vault_pass.txt
         ansible-vault decrypt ./deploy/.env-ci 
         ansible-vault decrypt ./deploy/nginx/default.conf
         cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
         mv deploy/.env-ci deploy/.env
#     - name: Collect static
#       run: |
#         cp deploy/.env .env
#         docker run \
#         --user 0 \
#         --rm \
#         -- env-file $(pwd)/deploy/.env \
#         --entrypoint '' \
#         -v $(pwd)/deploy/nginx/static/:/opt/todolist/static/:rm \
#         ${{ secrets.DOCKER_HUB_USERNAME }}/diplom_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID \
#         python manage.py collectstatic -c --no-input
     - name: copy files to server
       uses: appleboy/scp-action@master
       with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           source: "deploy/*"
           target: diplom
           strip_components: 1

     - name: run compose
       uses: appleboy/ssh-action@master
       with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
           script: |
             cd diplom
             docker compose up -d

     - name: clear after deploy
       if: always()
       uses: appleboy/ssh-action@master
       with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
               docker system prune -a -f